name: Staging Build Workflow

on:
  push:
    branches:
      - "staging"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - uses: docker/login-action@v1
      name: Login to DockerHub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - uses: docker/build-push-action@v2.7.0
      name: Build and PushBackend Image
      id: docker_build
      with:
        push: true
        tags: orgsinfo/cannon:latest
    
    - name: Cannon Backend Image Digest
      run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy the backend to the cluster
      uses: nickgronow/kubectl@master
      with:
        config_data: ${{ secrets.KUBE_CONFIG_DATA }}
        args: delete pod --selector="app=cannon-staging-app" --namespace=staging  